### ISSUE TITLE
Expected results?

### ISSUE THREAD

**Issue by rowanwins** [tchannel/turf-overlaps#1]
Gday @tcql 

Im just wondering about the expected results from this module.

In my scenario below I've got two polys, one is completely within the other, currently this is returning as false. So it seems like this only returns true if an edge intersection occurs?

I see you have another module [turf-polygon-within](https://github.com/tcql/turf-polygon-within) which probably gives me part of the answer however I would've thought that this module should perhaps call that module as well?

Thoughts?

Cheers
Rowan

```
var overlaps = require('turf-overlaps');

var poly1 = {"type": "Feature","properties": {},"geometry": {"type": "Polygon","coordinates": [[[-27.773437499999996,17.308687886770034],[-27.773437499999996,47.754097979680026],[15.468749999999998,47.754097979680026],[15.468749999999998,34.016241889667015],[28.828124999999996,34.016241889667015],[28.828124999999996,3.162455530237848],[-16.171875,3.162455530237848],[-16.171875,17.308687886770034],[-27.773437499999996,17.308687886770034]]]}};

var poly2 = {"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[-37.265625,-21.28937435586041],[-37.265625,60.413852350464914],[42.890625,60.413852350464914],[42.890625,-21.28937435586041],[-37.265625,-21.28937435586041]]]}};

var is_overlapping = overlaps(poly1, poly2);
```

**Comment by tcql** [comment]
actually, looks like I built `polygon-within` to rely on `overlaps` - overlaps is just looking for whether the shapes cross. 

I think I did it this way initially because this makes the implementation of `polygon-within` very simple - if the shapes don't overlap, and any single point of polygon _A_ is within polygon _B_, then _A_ is within _B_. All that being said, I haven't used either of the modules in quite awhile, they were mostly a proof of concept for simple spatial boolean operations (and neither is very robust right now)

**Comment by rowanwins** [comment]
awesome, thanks for the clarification. I'm currently using this in my dissolves module so I may need to rethink that part a little bit...
